### ISSUE TITLE
Korean translation support :)

### ISSUE THREAD

**Issue by SoYoungCho** [dformoso/machine-learning-mindmap#10]
Hi :) I'm SoYoung Cho, Kwangwoon University student in Korea!
I am working on a project - translating useful projects about machine learning.
And I think your repo is AMAZING and I'm sure this could help a lot of Korean studying ML.

So, may I translate these info in Korean?
If I could, please tell me how I can share the translated results!
Thank You :-)

**Comment by KimEJ** [comment]
this repository is protected by apache license. so if want use it, you just follow the license

**Comment by dformoso** [comment]
Hi there, apologies for the late reply (well, that's an understatement!). I've uploaded the original mindnode files now, so everyone can edit and add support for additional languages as desired.
