### ISSUE TITLE
References are still missing

### ISSUE THREAD

**Issue by danklotz** [dformoso/machine-learning-mindmap#4]
Hi there, 

the references are still missing. I cannot find my issue anymore. 

What happened?

**Comment by dformoso** [comment]
Hey danklotz,

You added references as an issue to my deep-learning repo and it's still there. This is the machine-learning repo. I haven't gotten around to adding those yet. Thanks for the reminder and for adding the issue to this repo.

**Comment by danklotz** [comment]
oh, missed that. Sorry :(

**Comment by dformoso** [comment]
Hi again, I've just added a few references. It's not a comprehensive list, but it's a start.

**Comment by prabhant** [comment]
which software you are using to make mind maps @dformoso

**Comment by dformoso** [comment]
I've built the mindmap with MindNode for the Mac. https://mindnode.com

**Comment by dformoso** [comment]
I've added as much references as I'm willing to add (not enough hours in the day!), but I'm open to get and approve pull requests on new references now that I've uploaded the mindnode files.
