### ISSUE TITLE
Mindmap file not included

### ISSUE THREAD

**Issue by ksnyde** [dformoso/machine-learning-mindmap#5]
Would you be willing to include the mindmap files as part of this repo?

**Comment by johndpope** [comment]
@dformoso - it would help because the dark theme styles aren't so printer friendly. 
you could enforce a credit at bottom or something.

**Comment by johndpope** [comment]
or you could consider releasing in a restricted way to users who want to contribute back to project.

**Comment by coomish** [comment]
I would also really appreciate to have access to the mindmap file OR having a version with a withe background for printing

**Comment by christiancoleman** [comment]
I love this idea. Please include them! @dformoso Or at least, which software did you make them in? :)

**Comment by dformoso** [comment]
Files added everyone!

**Comment by christiancoleman** [comment]
Wow! Thanks @dformoso! You're the man.
